[project]
name = "nofx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "flask>=3.1.2",
    "openai>=2.7.1",
    "requests>=2.32.5",
    "semantic-kernel>=1.36.0",
]
